services:
  postgres:
    image: postgres:16
    container_name: cmc_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: cmc_connect
      POSTGRES_USER: cmc_user
      POSTGRES_PASSWORD: cmc_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U cmc_user -d cmc_connect
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: