import { Bell, BriefcaseBusiness, FileCheck2, Send } from "lucide-react";
import DashboardShell from "@/components/DashboardShell";
import StatCard from "@/components/StatCard";
import OfferCard from "@/components/OfferCard";
import { offers } from "@/data/mock";
import Link from "next/link";

export default function CandidateDashboard() {
  return <DashboardShell role="candidate" title="Bonjour Mohammed 👋" subtitle="Votre profil stagiaire est prêt pour le matching."><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><StatCard label="Profil complété" value="92%" hint="CV confirmé + préférences" icon={FileCheck2}/><StatCard label="Offres compatibles" value="18" hint="score ≥ 65%" icon={BriefcaseBusiness}/><StatCard label="Candidatures" value="3" hint="dont 1 shortlistée" icon={Send}/><StatCard label="Notifications" value="2" hint="1 nouvelle aujourd'hui" icon={Bell}/></div><div className="mt-8 grid gap-6 xl:grid-cols-[1.5fr_.8fr]"><section><div className="flex items-end justify-between"><div><h2 className="section-title">Meilleures opportunités pour vous</h2><p className="mt-1 text-sm text-gray-500">Score calculé à partir du profil CV validé et de vos préférences.</p></div><Link href="/candidat/offres" className="text-sm font-bold text-cmc-teal-dark">Tout voir →</Link></div><div className="mt-5 grid gap-5 md:grid-cols-2">{offers.slice(0,4).map(o=><OfferCard key={o.id} offer={o}/>)}</div></section><aside className="space-y-5"><div className="card"><h2 className="section-title">Votre parcours</h2><div className="mt-5 space-y-4">{["CV déposé","Données extraites par IA","Profil validé","Préférences complétées"].map((x,i)=><div key={x} className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-50 text-xs font-bold text-emerald-700">✓</span><span className="text-sm font-semibold text-gray-700">{x}</span></div>)}</div><Link href="/candidat/profil" className="btn-secondary mt-6 w-full">Voir mon profil</Link></div><div className="rounded-xl bg-cmc-navy p-5 text-white"><p className="text-sm font-bold text-cmc-teal">Conseil matching</p><p className="mt-3 text-lg font-extrabold">Ajoutez AWS ou Spark à votre profil après acquisition réelle.</p><p className="mt-2 text-sm leading-6 text-white/60">Ce sont les écarts les plus fréquents dans vos offres Data compatibles.</p></div></aside></div></DashboardShell>;
}
