"""add candidate profile data

Revision ID: 043f25d7f0c5
Revises: 6cd63611564f
Create Date: 2026-07-17 17:13:54.140444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '043f25d7f0c5'
down_revision: Union[str, Sequence[str], None] = '6cd63611564f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profile_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_profile_id', sa.Integer(), nullable=False),
    sa.Column('cv_file_name', sa.String(length=255), nullable=True),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profile_data_candidate_profile_id'), 'candidate_profile_data', ['candidate_profile_id'], unique=True)
    op.create_index(op.f('ix_candidate_profile_data_id'), 'candidate_profile_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_profile_data_id'), table_name='candidate_profile_data')
    op.drop_index(op.f('ix_candidate_profile_data_candidate_profile_id'), table_name='candidate_profile_data')
    op.drop_table('candidate_profile_data')
    # ### end Alembic commands ###
