"""create job offers and applications

Revision ID: ed0ee79c464f
Revises: ebe5b1b187e4
Create Date: 2026-07-18 23:33:43.992429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ed0ee79c464f'
down_revision: Union[str, Sequence[str], None] = 'ebe5b1b187e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('skills_required', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('experience_required', sa.Integer(), nullable=True),
    sa.Column('education_level', sa.String(length=150), nullable=True),
    sa.Column('offer_type', sa.Enum('INTERNSHIP', 'EMPLOYMENT', name='job_offer_type_enum'), nullable=False),
    sa.Column('source', sa.Enum('CMC', 'SCRAPING', name='job_offer_source_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED', name='job_offer_status_enum'), nullable=False),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_offers_company_name'), 'job_offers', ['company_name'], unique=False)
    op.create_index(op.f('ix_job_offers_created_by_user_id'), 'job_offers', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_job_offers_id'), 'job_offers', ['id'], unique=False)
    op.create_index(op.f('ix_job_offers_location'), 'job_offers', ['location'], unique=False)
    op.create_index(op.f('ix_job_offers_offer_type'), 'job_offers', ['offer_type'], unique=False)
    op.create_index(op.f('ix_job_offers_source'), 'job_offers', ['source'], unique=False)
    op.create_index(op.f('ix_job_offers_status'), 'job_offers', ['status'], unique=False)
    op.create_index(op.f('ix_job_offers_title'), 'job_offers', ['title'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_offer_id', sa.Integer(), nullable=False),
    sa.Column('candidate_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'INTERVIEW', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='application_status_enum'), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('cv_file_name', sa.String(length=255), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_offer_id', 'candidate_profile_id', name='uq_application_offer_candidate')
    )
    op.create_index(op.f('ix_applications_candidate_profile_id'), 'applications', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_job_offer_id'), 'applications', ['job_offer_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_offer_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_profile_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_job_offers_title'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_status'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_source'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_offer_type'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_location'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_id'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_created_by_user_id'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_company_name'), table_name='job_offers')
    op.drop_table('job_offers')
    postgresql.ENUM(name='application_status_enum').drop(
        op.get_bind(),
        checkfirst=True,
    )
    postgresql.ENUM(name='job_offer_status_enum').drop(
        op.get_bind(),
        checkfirst=True,
    )
    postgresql.ENUM(name='job_offer_source_enum').drop(
        op.get_bind(),
        checkfirst=True,
    )
    postgresql.ENUM(name='job_offer_type_enum').drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
